<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="KOMAL" failures="2" tests="2" name="Default test(failed)" time="11.349" errors="0" timestamp="2023-01-05T14:16:22 IST">
  <testcase classname="TestCases.FailedTest" name="Test5" time="0.076">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.FailedTest.Test5(FailedTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test5 -->
  <testcase classname="TestCases.FailedTest" name="Test2" time="0.054">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.FailedTest.Test2(FailedTest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="TestCases.FailedTest" name="Test1" time="0.0">
    <ignored/>
  </testcase> <!-- Test1 -->
  <testcase classname="TestCases.FailedTest" name="Test4" time="0.0">
    <ignored/>
  </testcase> <!-- Test4 -->
  <testcase classname="TestCases.FailedTest" name="Test3" time="0.0">
    <ignored/>
  </testcase> <!-- Test3 -->
</testsuite> <!-- Default test(failed) -->
